# https://github.com/realm/SwiftLint/blob/master/Rules.md

disabled_rules:
- identifier_name # temporary disabled (https://github.com/realm/SwiftLint/issues/2231)

- conditional_returns_on_newline # this breaks simple code
- discouraged_object_literal # use object_literal instead of this
- explicit_type_interface # this kills simple code
- fallthrough # added new default rule no_fallthrough_only (https://github.com/realm/SwiftLint/pull/2194) instead of this
- file_header # no need for my project
- no_extension_access_modifier # use extension_access_modifier instead of this
- no_grouping_extension # this kills readable code

### !IMPORTANT!
### additional disabled rules for XCTest are in NowCastMapViewTests/.swiftlint.yml

opt_in_rules:
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- conditional_returns_on_newline
- contains_over_first_not_nila
- convenience_type
- discouraged_object_literal
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_count
- empty_string
- empty_ectest_method
- empty_xctest_method
- explicit_acl
- explicit_enum_raw_value
- explicit_init
- explicit_top_level_acl
- explicit_type_interface
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_header
- file_name
- first_where
- force_unwrapping
- function_default_parameter_at_end
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- no_grouping_extension
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefixed_toplevel_constant
- private_action
- private_outlet
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- required_enum_case
- single_test_class
- sorted_first_last
- sorted_imports
- strict_fileprivate
- switch_case_on_newline
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- vertical_parameter_alignment_on_call
- yoda_condition

excluded:
- Pods/
- Carthage/
- Example/

line_length:
- 200   # warning
- 300   # error

type_body_length:
- 400   # warning
- 600   # error

file_length:
- 500   # warning
- 1000  # error

function_body_length:
- 100   # warning
- 200   # error

function_parameter_count:
- 6     # warning
- 10    # error
